workflows:
  ios-testflight:
    name: Build iOS (IPA) and upload to TestFlight

    machine:
      type: mac-mini-xcode-15

    environment:
      flutter: stable
      vars:
        # --- REQUIRED: set these in Codemagic UI (or replace values here, but prefer secrets in UI) ---
        # Change APP_ID to your real bundle id in App Store Connect if different
        APP_ID: "com.lordbut.genevolut"
        APP_NAME: "Genevolut"

        # App Store Connect API key values (set in Codemagic Environment variables UI; mark sensitive)
        APP_STORE_CONNECT_KEY_ID: ""
        APP_STORE_CONNECT_ISSUER_ID: ""
        APP_STORE_CONNECT_PRIVATE_KEY_BASE64: "" # alternative: upload .p8 in Code signing UI instead of base64 here
        AUTO_PUBLISH_TO_TESTFLIGHT: "true"

      cache:
        cache_paths:
          - $HOME/.pub-cache
          - ios/Pods

    scripts:
      - name: Checkout code
        script: |
          echo "Workspace: $CM_WORKING_DIRECTORY"
      - name: Flutter pub get
        script: |
          flutter pub get
      - name: Ensure CocoaPods and prepare iOS dependencies
        script: |
          # install CocoaPods if missing (no-op if already present), then install pods
          brew install cocoapods || true
          cd ios || exit 1
          pod repo update || true
          pod install --repo-update || true
          cd ..
      - name: Run analyzer & optional tests
        script: |
          flutter analyze || true
          # flutter test  # uncomment to run tests (will fail build if tests fail)
      - name: (optional) set build number
        script: |
          BUILD_NUMBER=${CM_BUILD_ID:-$(date +%s)}
          echo "CI BUILD NUMBER: $BUILD_NUMBER"
          # If you want to inject build number into iOS project, handle it in Xcode or with agvtool on a Mac.
      - name: Build IPA (signed)
        script: |
          echo "Building iOS IPA (release) — no flavors used"
          # use ExportOptions.plist to control signing; this will use Codemagic signing configuration
          flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
      - name: Collect artifact paths
        script: |
          echo "Artifacts (IPA) should be in build/ios/ipa/"
          ls -la build/ios/ipa || true

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dsym.zip
      - build/**/app.dSYM.zip

    publishing:
      app_store_connect:
        auth_type: api_key
        api_key:
          key_id: ${APP_STORE_CONNECT_KEY_ID}
          issuer_id: ${APP_STORE_CONNECT_ISSUER_ID}
          private_key_base64: ${APP_STORE_CONNECT_PRIVATE_KEY_BASE64}
        bundle_id: ${APP_ID}
        team_name: ""
        app_name: ${APP_NAME}
        upload:
          testflight: ${AUTO_PUBLISH_TO_TESTFLIGHT}
