// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX9o-8-UWudggGlHTr38Bq6CBfuKRVgg4',
    appId: '1:1024647573688:web:680865cdd2e9ba8c6b844d',
    messagingSenderId: '1024647573688',
    projectId: 'alarmreminderapp-18fa2',
    authDomain: 'alarmreminderapp-18fa2.firebaseapp.com',
    storageBucket: 'alarmreminderapp-18fa2.firebasestorage.app',
    measurementId: 'G-RHWM7270E1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3g2K3_arGO1nQl9AZM_XFBdf_j9Txg8g',
    appId: '1:1024647573688:android:7b9d7aee88a33b4e6b844d',
    messagingSenderId: '1024647573688',
    projectId: 'alarmreminderapp-18fa2',
    storageBucket: 'alarmreminderapp-18fa2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_M9LFBbA6cx1qdXb-uvk5rsge_xOrZ9U',
    appId: '1:1024647573688:ios:c51e2927feadf1a06b844d',
    messagingSenderId: '1024647573688',
    projectId: 'alarmreminderapp-18fa2',
    storageBucket: 'alarmreminderapp-18fa2.firebasestorage.app',
    androidClientId: '1024647573688-j0jlj4f2flab3psh1gobal77dp0tc8er.apps.googleusercontent.com',
    iosClientId: '1024647573688-e1df4p3o5a4va1ip7othei641f050mr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.alarmreminderappios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_M9LFBbA6cx1qdXb-uvk5rsge_xOrZ9U',
    appId: '1:1024647573688:ios:c51e2927feadf1a06b844d',
    messagingSenderId: '1024647573688',
    projectId: 'alarmreminderapp-18fa2',
    storageBucket: 'alarmreminderapp-18fa2.firebasestorage.app',
    androidClientId: '1024647573688-j0jlj4f2flab3psh1gobal77dp0tc8er.apps.googleusercontent.com',
    iosClientId: '1024647573688-e1df4p3o5a4va1ip7othei641f050mr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.alarmreminderappios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX9o-8-UWudggGlHTr38Bq6CBfuKRVgg4',
    appId: '1:1024647573688:web:4704ca6509fb35866b844d',
    messagingSenderId: '1024647573688',
    projectId: 'alarmreminderapp-18fa2',
    authDomain: 'alarmreminderapp-18fa2.firebaseapp.com',
    storageBucket: 'alarmreminderapp-18fa2.firebasestorage.app',
    measurementId: 'G-88BC0L6VZS',
  );
}
